customhost = "employee.cgaao7yemqk4.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "tankianyangrobin-bucket"
customregion = "us-east-1"
